[package]
edition = "2021"
name = "usage_logger"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "usage_logger"

[dependencies]
serde = "1"
derive_more = "0"

hdk = {version = "0.0.127", features = ["encoding"]}
